#!/bin/bash

gpp_name="g++"
gmp_name="libgmp3-dev"
ssl_name="libssl-dev"
python_name="python3"
if command -v apt > /dev/null
then
	inst_manager="apt"
elif command -v yum > /dev/null
then
	inst_manager="yum"
    gpp_name="gcc-c++"
    gmp_name="gmp-devel"
    ssl_name="openssl-devel"
    python_name="python3-devel"
    version_append="m"
elif command -v brew > /dev/null
then
	inst_manager="brew"
else
	echo -e "No installation manager found, please install the requirements by hand.\n"
	exit
fi

#if [[ "$*" == *"python3"* ]]
#then
#	echo -e "Python3 is not installed...\nStarting installation\n"
#	sudo $inst_manager install $python_name
#    IFS=' '
#    read -a strarr <<< "$(python3 --version)"
#    IFS='.'
#    read -a strarr <<< "${strarr[1]}"
#    echo "${strarr[0]}.${strarr[1]}" >> .pyver.txt
#fi
ssl_crypto_installed=false
for i in "$@"; do
    case "$i" in
    "python3")
        echo -e "Python3 is not installed...\nStarting installation\n"
        sudo $inst_manager install $python_name
        IFS=' '
        read -a strarr <<< "$(python3 --version)"
        IFS='.'
        read -a strarr <<< "${strarr[1]}"
        echo "${strarr[0]}.${strarr[1]}$version_append" >> .pyver.txt
        shift;;
    "pip3")
        echo -e "pip3 is not installed...\nStarting installation\n"
        sudo $inst_manager install python3-pip
        shift;;
    "gcc")
        echo -e "Utility gcc is not installed...\nStarting installation\n"
        sudo $inst_manager install gcc
        shift;;
    "g++")
        echo -e "Utility g++ is not installed...\nStarting installation\n"
        sudo $inst_manager install $gpp_name
        shift;;
    "wget")
        echo -e "Utility wget is not installed...\nStarting installation\n"
        sudo $inst_manager install wget
        shift;;
    "gmp")
        echo -e "Library gmp is not installed...\nStarting installation\n"
        sudo $inst_manager install $gmp_name
        shift;;
    "ssl"|"crypto")
        if ! $ssl_crypto_installed
        then
            echo -e "Library ssl or crypto is not installed...\nStarting installation\n"
            sudo $inst_manager install $ssl_name
            ssl_crypto_installed=true
        fi
        shift;;
    -*|--*)
      echo -e "${RED}Unknown Requirements in: $@${NC}\n"
      exit 1;;
    *)
      ;;
    esac
done
#if [[ "$*" == *"pip3"* ]]
#then
#	echo -e "pip3 is not installed...\nStarting installation\n"
#	sudo $inst_manager install python3-pip
#fi
#
#if [[ "$*" == *"gcc"* ]]
#then
#	echo -e "Utility gcc is not installed...\nStarting installation\n"
#	sudo $inst_manager install gcc
#fi
#
#if [[ "$*" == *"g++"* ]]
#then
#	echo -e "Utility g++ is not installed...\nStarting installation\n"
#	sudo $inst_manager install $gpp_name
#fi
#
#if [[ "$*" == *"wget"* ]]
#then
#	echo -e "Utility wget is not installed...\nStarting installation\n"
#	sudo $inst_manager install wget
#fi
#
#if [[ "$*" == *"gmp"* ]]
#then
#	echo -e "Library gmp is not installed...\nStarting installation\n"
#	sudo $inst_manager install $gmp_name
#fi
#
#if [[ "$*" == *"ssl"* || "$*" == *"crypto"* ]]
#then
#	echo -e "Library ssl or crypto is not installed...\nStarting installation\n"
#	sudo $inst_manager install $ssl_name
#fi


if [ -f "requirements.txt" ]
then
    pip3 install -r requirements.txt
else
    if [ -f "../requirements.txt" ]
    then
        pip3 install -r ../requirements.txt
    else
        echo -e "ERROR: The requirements file has been moved, please perform a git pull to acquire it."
    fi
fi


