#!/bin/bash

mkdir boost_dir && cd boost_dir
wget https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.tar.gz
tar -xzvf boost_1_81_0.tar.gz
cd boost_1_81_0
python3_version="$(cat ../../.pyver.txt)"
echo -e "Installing boost with python${python3_version/m/}"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"/usr/include/python$python3_version"
./bootstrap.sh --with-libraries=python --with-python="python${python3_version/m/}" --with-toolset=gcc
sudo ./b2 install
cd ../..
